### ISSUE TITLE
Make sure Gutenberg column layouts are responsive

### ISSUE THREAD

**Issue by wpalchemist** [wpalchemist/tfc-nathan-small#5]

**Comment by wpalchemist** [comment]
Also, add padding, etc so the issues section on the homepage matches the design

**Comment by apennell** [comment]
@wpalchemist As far as I can tell, there isn't a built-in way to responsively change the number of columns. The ideal behavior is that there are 3 columns per row until 767px, and from there down there are only 2 per row. Is there a work-around that you usually apply? The mobile design only has the icon and title, so we could have a container with the 3-column layout and one with a 2-column layout and hide/show them depending on the screen width. Or we could just not worry about it and have it be 3 cols no matter what. Thoughts?

**Comment by apennell** [comment]
This has been completed for the issues section of the front page, aside from addressing the 2/3 responsive column issue.

I also changed the Gutenberg content on staging some to update the html for my CSS and also to add links to the issues page. Additionally, the Issues page has different styling and slightly different content than this child page issues section on the home page (as briefly discussed), so I updated the Issue link in the navigation menu to point to the standalone Issues page, /issues, rather than /nathan-on-the-issues. This is also the page that all the links in this front page issue section direct to. If this causes any problems with how you intended for it to work @wpalchemist please let me know!

**Comment by wpalchemist** [comment]
@apennell You should be able to use media queries to change the grid layout on smaller screens?

**Comment by apennell** [comment]
Ah okay. I'll take a closer look at the CSS they're using for the columns. Guess I take Bootstrap for granted 😁

**Comment by apennell** [comment]
@wpalchemist Just took a look at the column css and unfortunately it's not just a media query to take it from 3 down to 2 columns per row because it wraps the 3 columns in row divs :/ It's still "responsive," in that it shrinks down to fit the space, just doesn't have the ideal behavior of being rows of 2 on mobile, so I'm going to close this out.
